### ISSUE TITLE
Upgrade to JavaParser alpha-4

### ISSUE THREAD

**Issue by matozoid** [javaparser/java-symbol-solver#85]
I'm not pushy or anything :)

**Comment by ftomassetti** [comment]
I started moving on alpha-3 but then I got distracted. Well, we will move directly to alpha-4 then :D 

And maybe we could create one day a tool to automatically migrate projects from JavaParser 2 to JavaParser 3

**Comment by ftomassetti** [comment]
Superseded by #93
